### ISSUE TITLE
Detecting Shuffles

### ISSUE THREAD

**Issue by NamsajNiff** [scienceacademy/blackjack_bots#2]
It seems that you use the same instance of the bot for the entire game, this makes it almost impossible to detect when you are shuffling.

**Comment by cbscribe** [comment]
Good point. I'll patch something for that tomorrow.

**Comment by cbscribe** [comment]
Fixed. Your bot is now reinitialized when the shuffle happens. See `bot_human.py` for an example/demonstration.
